Repository open-rpc/generator, pull requests merged in 2019-05, with the labels that each got.

#166 Feat/cleaup interface
  README.md
  jest.config.js
  src/bootstrapGeneratedPackage.test.ts
  src/cli.ts
  src/index.test.ts
  src/index.ts
  templates/rust/static/Cargo.toml
  templates/rust/static/bin/test.sh
  templates/rust/static/src/lib.rs
  templates/rust/static/src/test_harness.rs
  templates/rust/templated/client.template.ts
  templates/typescript/static/_package.json
  templates/typescript/static/gitignore
  templates/typescript/static/package-lock.json
  templates/typescript/static/src/index.ts
  templates/typescript/static/tsconfig.json
  templates/typescript/static/tslint.json
  templates/typescript/templated/exported-class.template.ts
Labels: enhancement

#173 fix: cli passing wrong arg
  src/cli.ts
Labels: bug

#175 feat: add --version to cli
  package-lock.json
  src/cli.ts
Labels: enhancement

#178 Fix/linting
  package-lock.json
  package.json
  src/cli.ts
  tslint.json
Labels: bug

#180 fix: remove out of date information
  README.md
Labels: bug

#192 feat(rust): handle complex openrpc documents
  package-lock.json
  package.json
  src/index.ts
Labels: bug

#188 fix: output validation errors
  src/cli.ts
Labels: bug

#194 fix: use open-rpc client-js instead of Jayson
  package-lock.json
  src/index.ts
  templates/typescript/static/_package.json
  templates/typescript/static/package-lock.json
  templates/typescript/templated/exported-class.template.ts
Labels: enhancement

#200 fix: add ts-name config for package json name + rs-name for crate
  README.md
  package-lock.json
  package.json
  src/cli.ts
  src/index.test.ts
  src/index.ts
Labels: enhancement

#208 fix: add description and license to Cargo.toml
  templates/rust/static/Cargo.toml
Labels: bug

#210 Feat/typings api
  package-lock.json
  package.json
  templates/rust/templated/client.template.ts
  templates/typescript/static/tslint.json
  templates/typescript/templated/exported-class.template.ts
Labels: enhancement

#221 fix: update schema utils
  package-lock.json
  package.json
Labels: bug, dependencies

#222 fix: use latest schema-utils for client
  templates/typescript/static/_package.json
  templates/typescript/static/package-lock.json
Labels: bug

#224 fix: ajv not used
  templates/typescript/templated/exported-class.template.ts
Labels: bug
