Repository open-rpc/generator, pull requests merged in 2019-04, with the labels that each got.

#129 feat: awesome badges
  README.md
Labels: enhancement

#157 WIP Fix/maint
  package-lock.json
  package.json
  src/generators/generator-interface.ts
  src/generators/index.ts
  src/generators/rust.ts
  src/generators/typescript.ts
  src/index.test.ts
  src/index.ts
  templates/js/static/_package.json
  templates/js/static/package-lock.json
  templates/js/templated/exported-class.template.ts
  templates/rs/templated/client.template.ts
Labels: bug, dependencies, enhancement

#158 Fix/cli build
  .node-version
  bin/cli.js
  bin/get-version.js
  package-lock.json
  package.json
  src/cli.ts
  src/get-version.ts
Labels: bug

#161 fix: remove publish step
  package.json
Labels: bug

#162 fix: version is breaking release
  package.json
  src/cli.ts
  src/get-version.ts
Labels: bug

#163 Fix(rust): update the autorand crate version
  templates/rs/static/Cargo.toml
Labels: bug

#164 Fix/cli bin
  package.json
  src/cli.ts
Labels: bug
